### PR TITLE
Fixed Hello world example in Readme.md

### PR DESCRIPTION
**Pull request by david-zwicker**
I turned the example into a script that runs and gives some output.

Changes:
* Replaced `mpi` by `numba_mpi` in two places
* Call the compiled function `hello`

### CODE REVIEW

**Comment by slayoo** [comment]
Thank you, @david-zwicker! 
It seems it fails within the send function as the backend routine is not returning 0 (MPI_SUCCESS).
These asserts anyhow certainly need to be moved out of the functions probably:
- returning the error code to the caller instead and
- doing such asserts within unit tests instead
Will follow up soon... (and thanks again!)

**Comment by slayoo** [comment]
closing and reopening to run tests with updated workflow from the main branch (where the readme code is also executed using `mpiexec`)

**Comment by slayoo** [comment]
OK, makes sense - the send does not work if run without `mpiexec`

**Comment by david-zwicker** [comment]
Yeah, it's not surprising that this doesn't run so easily. One could of course remove the call to `hello`, so the test passes.

**Comment by slayoo** [comment]
I've just removed non-mpi execution of the README snippets from the CI workflow: https://github.com/atmos-cloud-sim-uj/numba-mpi/commit/32e760456f466a490ea71352ed8bbcaf57f80db1
It's clearly essential to have the `hello` function actually executed in this snippet, thanks very much for noticing and correcting it!
I'll close and reopen again to re-trigger checks again current master, then merge and make a new release.

**Pull request merged**
